### ISSUE TITLE
Make it a configurable option that pillagers may spawn by chance with musket naturally

### ISSUE THREAD

**Issue by betterworld-sjq** [BrokenK3yboard/SimpleMusket#1]
Pillagers are too weak and they need a chance (if configurable, that's better!)  to get a more powerful weapon! Even not in raids
By the way, could you make some apparent effect around the gun mouth like flame fire or sth, to tell that the ammo is shot

**Comment by BrokenK3yboard** [comment]
Won't happen until there are behavior reworks and better telegraphing of when musketeers/marksmen are shooting at the player. As of now they shoot the player with 0 noise at longer ranges while ignoring half their armor.
