### ISSUE TITLE
1.21 Entity Ticking with Friends & Foes mod

### ISSUE THREAD

**Issue by makumaku1974** [BrokenK3yboard/SimpleMusket#11]
Log :https://mclo.gs/MTTU12H
Crash Report: https://mclo.gs/HMT0X5u

I was using simple musket to try test out the Friends & Foes Iceologer.. I

**Comment by BrokenK3yboard** [comment]
What do you mean "test out"? Because other mods are likely involved you will have to see which one causes this crash when installed. I have shot an F&F Iceologer without issue.

**Comment by makumaku1974** [comment]
The "test out" was to shoot mobs and tbf im only reporting crashes based on mclogs because i cant read codes. Some mods are still in beta despite being released in modrinth. Apologise though if it was sudden.

**Comment by makumaku1974** [comment]
Apologies again, this is actually caused by a new mod. I will close this issue now.
