### ISSUE TITLE
Crash on startup after updating Fabric API

### ISSUE THREAD

**Issue by vico93** [BrokenK3yboard/SimpleMusket#12]
Got [this crash](https://gist.github.com/vico93/30e1564151b6e0d20c8608696491f500) when booting the game after updating Fabric API to 0.101.0.

simplemusket-fabric-1.21-1.8.0

**Comment by BrokenK3yboard** [comment]
Try updating to Fabric 0.102.0. This might have been an issue on their end.

**Comment by vico93** [comment]
> Try updating to Fabric 0.102.0. This might have been an issue on their end.

For me mod still crashes in 0.102.0.

**Comment by BrokenK3yboard** [comment]
You will need to post logs and provide a modlist. I do not crash when running 1.8.0 in 0.102.

**Comment by vico93** [comment]
I will resume testing as soon Indium (one of the mods i'm using) gets an update to 1.21.1, since i'm in the process of updating my modpack to that version.

**Comment by vico93** [comment]
Just updated to the latest version, seems to work fine.

But it still marked as 1.21-only, including [extensibleenums](https://github.com/Fuzss/extensibleenums), even though it have a proper 1.21.1 version on github.
![image](https://github.com/user-attachments/assets/fa7044db-2e8c-445a-80f4-ff1c07203b2a)

**Comment by BrokenK3yboard** [comment]
I am waiting for a response from Fuzs to see if extensibleenums can cover both versions. The 1.21.1 version of extensible enums was uploaded earlier today and does not allow for usage with 1.21, and I do not want to maintain two separate versions.
