### ISSUE TITLE
Make the damage of each bullet configurable

### ISSUE THREAD

**Issue by betterworld-sjq** [BrokenK3yboard/SimpleMusket#3]
This would do enormous help to balance the modpack. Because in my modpack, where outstanding weapons fill the sky, the musket seems totally useless among them. I want the musket to be a good option to deal with highly-armored mobs. Grave gratitude in advance!

**Comment by mpustovoi** [comment]
Why not? A musket is weaker than a wooden sword with its 4 base damage. It's just worthless.
If the damage was at least 15, it would make sense.
