### ISSUE TITLE
Better Combat / Epic Fight compatibility

### ISSUE THREAD

**Issue by donmor** [BrokenK3yboard/SimpleMusket#6]
For those who want better combat motions or soul-like experience, they prefer adding those two mods into their modpack. I wonder if aiming anims data could be added into this mod... Or even having Gun Fu XD

**Comment by BrokenK3yboard** [comment]
Better Combat doesn't seem to affect ranged weapons and from the looks of it neither does Epic Fight, so I'm not sure what compatibility you're asking for. I also don't see the point in giving a melee move set to a ranged weapon that has no melee damage bonuses.
