### ISSUE TITLE
About 1.20.4

### ISSUE THREAD

**Issue by vico93** [BrokenK3yboard/SimpleMusket#7]
Hi! Is this mod compatible with 1.20.4? And if not, do you have plans to update for that version?

**Comment by BrokenK3yboard** [comment]
I don't use 1.20.4, and the latest version has received less than 1,000 downloads in the past month despite adding fabric support and improvements. No reason for me to update.

**Comment by vico93** [comment]
> I don't use 1.20.4, and the latest version has received less than 1,000 downloads in the past month despite adding fabric support and improvements. No reason for me to update.

Then at least can other modders fork & update it to 1.20.4? Since it's GPL...
