### ISSUE TITLE
Consecration integration for Fabric does not work.

### ISSUE THREAD

**Issue by Karthsteel** [BrokenK3yboard/SimpleMusket#8]
Says what it does on the tin. I have consecration installed, and enchanted rounds do not show up. If I spawn them in and fire them, they either do not load or they don't work as intended. Using the latest release for Fabric on Modrinth. Thanks for reading!

**Comment by BrokenK3yboard** [comment]
The fabric version of Consecration does not have the functionality needed to make this work last I checked. The mod page should mention this is a Neo/Forge only feature.

**Comment by Karthsteel** [comment]
Ah, thanks! I likely skimmed over that. Thanks for the quick reply!
