### ISSUE TITLE
[1.20.1 / Fabric] Entity being killed causes a crash.

### ISSUE THREAD

**Issue by tivvo** [BrokenK3yboard/SimpleMusket#9]
this same bug happens with HWG, with bullets (from the smg)
happens specifically when a player is killed

[crash-2024-05-16_18.36.56-server.txt](https://github.com/BrokenK3yboard/SimpleMusket/files/15339599/crash-2024-05-16_18.36.56-server.txt)

**Comment by BrokenK3yboard** [comment]
This is likely being caused by "Discord Integration Fabric", seeing as how two different mods are getting the exact same crash.

**Comment by tivvo** [comment]
weird, wonder why its causing a crash
i'd assume maybe a bug with how the way it handles entity bullet kills with both of the mods because it keeps spewing out a null value

**Comment by tivvo** [comment]
i'll go make a pull request on it and see what happens
